[settings]
experimental = true

[tools]
rust = "1.95.0"

[env]
PROJECT_NAME = "{{ config_root | basename }}"
CARGO_BUILD_TARGET = "wasm32-wasip1"
TARGET_DIR = "{{ config_root }}/target/{{ env.CARGO_BUILD_TARGET }}"
DEBUG_WASM = "{{ env.TARGET_DIR }}/debug/{{ env.PROJECT_NAME }}.wasm"
RELEASE_WASM = "{{ env.TARGET_DIR }}/release/{{ env.PROJECT_NAME }}.wasm"
DEMO_CAST = "{{ config_root }}/assets/demo.cast"
DEMO_GIF = "{{ env.DEMO_CAST }}.gif"

[hooks]
postinstall = "rustup target add {{ env.CARGO_BUILD_TARGET }}"

[tasks."build:release"]
run = "cargo build --release"

[tasks.build]
alias = "b"
run = "cargo build"

[tasks.lint]
alias = "l"
run = "cargo clippy"

[tasks.fix]
alias = "f"
run = "cargo clippy --allow-dirty --fix"

[tasks.run]
alias = "r"
depends = "build"
run = "zellij action start-or-reload-plugin file:{{ env.DEBUG_WASM }}"

[tasks."demo:record"]
tools = { "aqua:asciinema/asciinema" = "latest" }
run = "asciinema record {{ env.DEMO_CAST }} -I --overwrite --title '{{ env.PROJECT_NAME }} demo'"

[tasks."demo:astroterm"]
run = "astroterm -c -s 200 -C -f 60"

[tasks."demo:to-gif"]
tools = { "aqua:asciinema/agg" = "latest" }
run = "agg {{ env.DEMO_CAST }} {{ env.DEMO_GIF }}"

[tasks."demo:play"]
tools = { "aqua:asciinema/asciinema" = "latest" }
run = "asciinema play {{ env.DEMO_CAST }}"
